### ISSUE TITLE
疑问？

### ISSUE THREAD

**Issue by Lizhooh** [hustcc/onfire.js#7]
为什么？
触发事件是用 onfire.fire 而不是 onfire.emit 
取消绑定是用 onfire.un 而不是 onfire.off

**Comment by hustcc** [comment]
取个名字而已。都可以的！

生产环境不建议使用这个模块。

**Comment by Lizhooh** [comment]
@hustcc 为什么在生产环境不建议使用这个模块？

**Comment by hustcc** [comment]
testeases写的不够完善，建议用相同功能的其它模块。
